# Generated by Django 5.1.1 on 2025-01-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0003_ordermodel_latitude_ordermodel_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='longitude',
        ),
    ]
