# Generated by Django 5.1.1 on 2025-01-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0004_remove_ordermodel_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='distance_km',
        ),
    ]
