# Generated by Django 5.1.1 on 2025-01-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0005_remove_ordermodel_distance_km'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='lat',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='lon',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
