# Generated by Django 5.1.1 on 2025-01-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orders', '0006_ordermodel_lat_ordermodel_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
