# Generated by Django 5.1.1 on 2025-01-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
