# Generated by Django 5.1.1 on 2025-01-23 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foods', '0003_alter_usermodel_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='orderitemmodel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='app_foods.ordermodel'),
        ),
    ]
