# Generated by Django 5.1.1 on 2025-01-31 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='preparation_time',
        ),
    ]
