# Generated by Django 5.1.1 on 2025-01-31 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_longitude',
            new_name='longitude',
        ),
    ]
