# Generated by Django 5.1.1 on 2025-02-02 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_delivery_latitude_order_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_fee',
        ),
    ]
