# Generated by Django 5.1.1 on 2025-02-03 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_menuitem_preparation_time'),
        ('orders', '0004_remove_order_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='menu_item',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='menu.menuitem'),
            preserve_default=False,
        ),
    ]
